app:
  timezone: "Asia/Seoul"
  run_time_hour: 8
  lookback_hours: 24
  max_items_per_subcategory: 5
  selection_mode: "scored"   # "scored": 휴리스틱+AI 일부 / "recent": 최신순만

sources:
  google_news:
    base: "https://news.google.com/rss/search"
    hl: "ko"
    gl: "KR"
    ceid: "KR:ko"

email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  use_tls: true
  username: "keullipingnyuseu@gmail.com"
  password_env: "SMTP_PASSWORD"
  from_name: "정유 뉴스봇"
  from_addr: "keullipingnyuseu@gmail.com"
  to_addrs:
    - "sm.joo@gscaltex.com"
    - "wh.lee@gscaltex.com"
    - "recca@gscaltex.com"
    - "kahlee@gscaltex.com"
    - "kwy@gscaltex.com"
    - "nkk@gscaltex.com"
    - "mklee@gscaltex.com"
    
  subject_prefix: "[이원호 사원의 특수영업팀 일일 정유 뉴스]"

openai:
  enable_ai_filter: true
  relevance_model: "gpt-4o-mini"
  relevance_max_checks: 40
  relevance_delay_secs: 1.0
  relevance_backoff_secs: 8
  relevance_threshold: 0.65
  api_key_env: "OPENAI_API_KEY"

filters:
  block_domains:
    - "blog.naver.com"
    - "m.blog.naver.com"
    - "tistory.com"
    - "medium.com"
    - "brunch.co.kr"
    - "velog.io"
  block_keywords:
    - "대통령"
    - "총선"
    - "대선"
    - "국회"
    - "여당"
    - "야당"
    - "민주당"
    - "국민의힘"
    - "정당"
    - "정치인"
    - "극우"
    - "극좌"
    - "내란"
    - "진보"
    - "보수"
    - "연예"
    - "가수"
    - "배우"
    - "아이돌"
    - "드라마"
    - "예능"
    - "유튜버"
    - "인플루언서"
    - "Vietnam"
    - "테마"
    - "토픽"
    - "반도체"
    - "지하철"
    - "교육"
    - "청렴"
    - "윤리"
    - "상호존중"
    - "망망대해"
    - "동료"
    

scoring:
  base: 0.0
  fuel_core_terms:
    terms: ["경유","휘발유","등유","항공유","VLSFO","LSFO","MF380","벙커C유","중유","ULSD","MGO","Gasoil","Gasoline","Kerosene","Jet A-1","JP-5","JP-8","아스팔트","AP-5"]
    weight: 1.0
  demand_signals:
    terms: ["차량 증가","신차 등록","물류 증가","교통량 증가","고속도로 통행량","여객 증가","승객 수","탑승률","항공 수요","조업 재개","조업 증가","어획량 증가","어선 증가","출어 횟수","풍어","훼리 증가","여객선 증가","항로 신설","항로 증편","운항 재개","운항 증가","컨테이너 물동량","항만 물동량","해상 물동량","화물 증가","건설 수요","도로 건설","아스콘 발주","아스팔트 발주","한파","폭염","난방 수요","냉방 수요","명절 귀성","연휴 이동","성수기"]
    weight: 2.5
  price_signals:
    terms: ["유가 상승","유가 급등","유가 하락","국제 유가","정제마진","크랙 스프레드","스프레드","휘발유 가격","경유 가격","항공유 가격","아스팔트 가격","중유 가격","석유 제품 가격","공장도가","국내 가격 인상","국내 가격 인하","세금 인상","세금 인하","OSP","OPEC 감산","증산","재고 감소","재고 증가"]
    weight: 3.0
  ops_supply_signals:
    terms: ["조달","입찰","발주","공급 계약","장기 공급","정유사 가동","정비","정지","재가동","가동률","파업","노사","물류대란","항만 정체","제한 속도 해제","긴급 수송","연료 사용 확대","환경 규제","유황 규제","IMO","스크러버"]
    weight: 1.5
  soft_penalty:
    terms: ["정당","선거","연예","예능","유튜버"]
    weight: -3.0
  noise_tokens:
    terms: ["[속보]","속보","[단독]","단독","[영상]","[포토]"]
    weight: -0.2

taxonomy:
  - major: "특수영업팀 전체"
    minor: "국제 유가 뉴스"
    keywords:
      - "유가"
      - "정제마진"
      - "Dubai"
      - "WTI"
      - "석유"

  - major: "특수영업팀 전체"
    minor: "정유4사"
    keywords:
      - "S-OIL"
      - "SK에너지"
      - "HD현대오일뱅크"
      - "GS칼텍스"

  - major: "특수영업팀 전체"
    minor: "그룹사"
    keywords:
      - "GS"
      - "지에스"

  - major: "유종별"
    minor: "경유"
    keywords:
      - "경유"
      - "ULSD"
      - "0.05%MGO"
      - "선박연료유"
      - "해상유"
      - "디젤"
      - "초저유황경유"
      - "Gasoil"

  - major: "유종별"
    minor: "휘발유"
    keywords:
      - "휘발유"
      - "Mogas"
      - "Gasoline"

  - major: "유종별"
    minor: "항공유"
    keywords:
      - "Jet A-1"
      - "JP-5"
      - "JP-8"
      - "항공유"

  - major: "유종별"
    minor: "등유"
    keywords:
      - "등유"
      - "Kero"
      - "Kerosene"

  - major: "유종별"
    minor: "중유"
    keywords:
      - "VLSFO"
      - "LSFO"
      - "MF380"
      - "벙커C유"
      - "중유"
      - "선박연료유"
      - "해상유"
      - "스크러버"

  - major: "유종별"
    minor: "아스팔트"
    keywords:
      - "아스팔트"
      - "AP-5"
      - "친환경 아스팔트"
      - "중국 아스팔트"
      - "도로 건설"
      - "고속도로 공사"
      - "국도"
      - "개량"
      - "SOC 예산"
      - "SOC"
      - "개질 아스팔트"
      - "배수성 아스팔트"
      - "순환 아스팔트"
      - "특수 아스팔트"

  - major: "채널별"
    minor: "국군납"
    keywords:
      - "육군"
      - "해군"
      - "공군"
      - "해병대"
      - "국군"
      - "유류보급"

  - major: "채널별"
    minor: "철도공사"
    keywords:
      - "철도공사"
      - "Korail"
      - "차량사업소"
      - "특별동차운영단"

  - major: "채널별"
    minor: "한전"
    keywords:
      - "한전"
      - "한국전력"
      - "남동발전"
      - "중부발전"
      - "서부발전"
      - "남부발전"
      - "동서발전"
      - "태안발전"
      - "당진발전"
      - "남제주발전"
      - "고성그린파워"
      - "강릉에코파워"
      - "여수발전"
      - "삼천포발전"
      - "영흥발전"
      - "서천발전"
      - "강릉안인발전"
      - "영동발전"
      - "도서발전"

  - major: "채널별"
    minor: "해양경찰청"
    keywords:
      - "해경"
      - "해양경찰청"
      - "선박급유업"

  - major: "채널별"
    minor: "수협"
    keywords:
      - "수협"
      - "수협중앙회"
      - "어업면세유"
      - "금어기"
      - "어획량"
      - "어선"
      - "풍랑주의보"
      - "조업중단"
      - "적조현상"
      - "수온상승"
      - "어선척수"
      - "감척"
      - "수산자원량"
      - "출어횟수"
      - "어선현대화"
      - "연근해어업"
      - "친환경어선"
      - "고등어"
      - "꽃게"
      - "풍어"

  - major: "채널별"
    minor: "해운조합"
    keywords:
      - "해운조합"
      - "여객선"
      - "연안해운"
      - "내항화물선"
      - "씨월드고속훼리"
      - "한일고속"
      - "선박현대화"
      - "친환경선박"
      - "여객선 항로신설"
      - "여객선 항로결항"
      - "여객선 항로중단"
      - "훼리"
      - "여객선"

  - major: "채널별"
    minor: "해상유대리점"
    keywords:
      - "준설사업"
      - "간척사업"
      - "풍력사업"
      - "매립현장"
      - "준설"
      - "간척"
      - "면세유불법유통"

  - major: "채널별"
    minor: "아스콘"
    keywords:
      - "한석유화"
      - "다온"
      - "라우러스"
      - "선웅"
      - "씨앤씨"
      - "영진상사"
      - "제이앤드디"
      - "한국석유"
      - "창포기술"
