app:
  timezone: "Asia/Seoul"
  run_time_hour: 8
  lookback_hours: 24
  max_items_per_subcategory: 5
  language: "ko"
  country: "KR"

openai:
  enable_ai_filter: true
  relevance_model: "gpt-4o-mini"
  relevance_max_checks: 30     # ★ 실행당 최대 30개만 AI 필터 돌림
  relevance_delay_secs: 1.0    # 호출 간 딜레이
  relevance_backoff_secs: 8
  relevance_threshold: 0.6     # 보수적으로 true만 살림

sources:
  google_news:
    base: "https://news.google.com/rss/search"
    hl: "ko"
    gl: "KR"
    ceid: "KR:ko"

email:
  smtp_host: "smtp.gmail.com"        # 실제 SMTP 서버 주소로 교체
  smtp_port: 587
  use_tls: true
  username: "keullipingnyuseu@gmail.com" # 실제 계정
  password_env: "SMTP_PASSWORD"
  from_name: "정유사 AI 뉴스봇"
  from_addr: "keullipingnyuseu@gmail.com"
  to_addrs:
    - "wh.lee@gscaltex.com"
  subject_prefix: "[정유 뉴스 요약]"



  # (AI 필터링) 강력 필터 옵션
  enable_ai_filter: true
  relevance_model: "gpt-4o-mini"     # 분류에 사용할 모델
  relevance_max_checks: 30           # 실행 1회당 최대 AI 판별 호출 수(예: 전체 후보 중 상위 80개만 AI 판별)
  relevance_delay_secs: 0.8          # 호출간 딜레이
  relevance_backoff_secs: 15         # 429 시 대기
  relevance_threshold: 0.5           # 0~1, '관련' 확신도 임계값(0.5 권장)

filters:
  block_domains:
    - "blog.naver.com"
    - "m.blog.naver.com"
    - "tistory.com"
    - "medium.com"
    - "brunch.co.kr"
    - "velog.io"

  # 완전 차단(등장하면 즉시 제외)
  block_keywords:
    # 정치
    - "민주"
    - "보수"    
    - "우파"
    - "극우"
    - "국회"
    - "여당"
    - "야당"
    - "민주당"
    - "국민의힘"
    - "정당"
    - "정치인"
    - "전한길"
    - "극좌"
    - "진보"
    - "사전경유제"
    - "경유하다"
    - "경유해"
    - "내란"
    - "애국"
    - "Vietnam"
    - "vm"
    - "두카티"
    - "잡초"
    - "방화범"
  
    # 연예/문화/스포츠(대표)
    - "가수"
    - "배우"
    - "아이돌"
    - "드라마"
    - "예능"
    - "유튜버"
    - "인플루언서"
    - "장혁"
    - "BTS"
    - "성우"

  political_noise_keywords:
    - "우파"
    - "좌파"
    - "진보"
    - "보수"
    - "정당"
    - "선거"
    - "총선"
    - "대선"
    - "국회"

  soft_noise_keywords:
    - "연예"
    - "게임"
    - "SNS"
    - "유튜버"
    - "루머"
    - "썰"

scoring:
  base_match: 1.0
  refinery_relevance:
    fuel_terms:
      - "경유"
      - "휘발유"
      - "등유"
      - "항공유"
      - "VLSFO"
      - "ULSD"
      - "MGO"
      - "Gasoil"
      - "Gasoline"
      - "Kerosene"
      - "Jet A-1"
      - "JP-5"
      - "JP-8"
      - "아스팔트"
      - "AP-5"
      - "친환경 아스팔트"
      - "특수아스팔트"
    weight: 2.0
  political_penalty:
    terms: ["우파","좌파","진보","보수","정당","선거","총선","대선","국회"]
    weight: -3.0
  soft_penalty:
    terms: ["연예","게임","SNS","유튜버","루머","썰"]
    weight: -2.0
  unrelated_penalty:
    weight: -1.0

taxonomy:
  - major: "특수영업팀 전체"
    minor: "국제 유가 뉴스"
    keywords: ["유가", "정제마진", "Dubai", "WTI", "석유"]

  - major: "특수영업팀 전체"
    minor: "정유4사"
    keywords: ["S-OIL", "SK에너지", "HD현대오일뱅크", "GS칼텍스"]

  - major: "특수영업팀 전체"
    minor: "그룹사"
    keywords: ["GS", "지에스"]

  - major: "유종별"
    minor: "경유"
    keywords: ["경유", "ULSD", "0.05%MGO", "선박연료유", "해상유", "디젤", "초저유황경유", "Gasoil"]

  - major: "유종별"
    minor: "휘발유"
    keywords: ["휘발유", "Mogas", "Gasoline"]

  - major: "유종별"
    minor: "항공유"
    keywords: ["Jet A-1", "JP-5", "JP-8", "항공유"]

  - major: "유종별"
    minor: "등유"
    keywords: ["등유", "Kero", "Kerosene"]

  - major: "유종별"
    minor: "중유"
    keywords: ["VLSFO", "LSFO", "MF380", "벙커C유", "중유", "선박연료유", "해상유", "스크러버"]

  - major: "유종별"
    minor: "아스팔트"
    keywords: ["아스팔트", "AP-5", "친환경 아스팔트", "중국 아스팔트", "도로 건설", "특수아스팔트"]

  - major: "채널별"
    minor: "국군납"
    keywords: ["육군", "해군", "공군", "해병대", "국군", "유류보급"]

  - major: "채널별"
    minor: "철도공사"
    keywords: ["철도공사", "Korail", "차량사업소", "특별동차운영단"]

  - major: "채널별"
    minor: "한전"
    keywords: ["한전", "한국전력", "남동발전", "중부발전", "서부발전", "남부발전", "동서발전",
               "태안발전", "당진발전", "남제주발전", "고성그린파워", "강릉에코파워", "여수발전",
               "삼천포발전", "영흥발전", "서천발전", "강릉안인발전", "영동발전", "도서발전"]

  - major: "채널별"
    minor: "해양경찰청"
    keywords: ["해경", "해양경찰청", "선박급유업"]

  - major: "채널별"
    minor: "수협"
    keywords: ["수협", "수협중앙회", "어업면세유", "금어기", "어획량", "어선", "풍랑주의보", "조업중단",
               "적조현상", "수온상승", "어선척수", "감척", "수산자원량", "출어횟수", "어선현대화",
               "연근해어업", "친환경어선", "고등어", "꽃게", "풍어"]

  - major: "채널별"
    minor: "해운조합"
    keywords: ["해운조합", "여객선", "연안해운", "내항화물선", "씨월드고속훼리", "한일고속",
               "선박현대화", "친환경선박", "여객선 항로신설", "여객선 항로결항", "여객선 항로중단",
               "훼리", "여객선"]

  - major: "채널별"
    minor: "해상유대리점"
    keywords: ["준설사업", "간척사업", "풍력사업", "매립현장", "준설", "간척", "면세유불법유통"]

  - major: "채널별"
    minor: "아스콘"
    keywords: ["한석유화", "다온", "라우러스", "선웅", "씨앤씨", "영진상사", "제이앤드디", "한국석유", "창포기술"]
